# Generated by Django 2.1.7 on 2019-03-09 21:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_app', '0002_auto_20190223_2040'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelMessage',
            new_name='Message',
        ),
        migrations.RenameModel(
            old_name='ModelRoom',
            new_name='Room',
        ),
    ]
